tablero(celda(5,6,0),ficha(1,in))[source(self)].
tablero(celda(0,4,0),ficha(4,in))[source(self)].
tablero(celda(9,2,0),ficha(5,in))[source(self)].
tablero(celda(7,4,0),ficha(3,in))[source(self)].
tablero(celda(2,3,0),ficha(1,in))[source(self)].
tablero(celda(4,1,0),ficha(3,in))[source(self)].
tablero(celda(9,3,0),ficha(0,in))[source(self)].
tablero(celda(3,8,0),ficha(5,in))[source(self)].
tablero(celda(6,0,0),ficha(0,in))[source(self)].
tablero(celda(3,9,0),ficha(0,in))[source(self)].
tablero(celda(5,7,0),ficha(2,in))[source(self)].
tablero(celda(0,5,0),ficha(5,in))[source(self)].
tablero(celda(7,5,0),ficha(4,in))[source(self)].
tablero(celda(1,8,0),ficha(1,in))[source(self)].
tablero(celda(8,8,0),ficha(0,in))[source(self)].
tablero(celda(3,6,0),ficha(3,in))[source(self)].
tablero(celda(5,4,0),ficha(5,in))[source(self)].
tablero(celda(5,5,0),ficha(0,in))[source(self)].
tablero(celda(0,3,0),ficha(3,in))[source(self)].
tablero(celda(2,1,0),ficha(5,in))[source(self)].
tablero(celda(9,1,0),ficha(4,in))[source(self)].
tablero(celda(7,3,0),ficha(2,in))[source(self)].
tablero(celda(2,2,0),ficha(0,in))[source(self)].
tablero(celda(4,0,0),ficha(2,in))[source(self)].
tablero(celda(1,9,0),ficha(2,in))[source(self)].
tablero(celda(8,9,0),ficha(1,in))[source(self)].
tablero(celda(3,7,0),ficha(4,in))[source(self)].
tablero(celda(6,8,0),ficha(2,in))[source(self)].
tablero(celda(1,6,0),ficha(5,in))[source(self)].
tablero(celda(8,6,0),ficha(4,in))[source(self)].
tablero(celda(1,7,0),ficha(0,in))[source(self)].
tablero(celda(3,5,0),ficha(2,in))[source(self)].
tablero(celda(5,3,0),ficha(4,in))[source(self)].
tablero(celda(0,2,0),ficha(2,in))[source(self)].
tablero(celda(2,0,0),ficha(4,in))[source(self)].
tablero(celda(9,0,0),ficha(3,in))[source(self)].
tablero(celda(7,2,0),ficha(1,in))[source(self)].
tablero(celda(6,9,0),ficha(3,in))[source(self)].
tablero(celda(8,7,0),ficha(5,in))[source(self)].
tablero(celda(4,8,0),ficha(4,in))[source(self)].
tablero(celda(0,0,0),ficha(0,in))[source(self)].
tablero(celda(6,7,0),ficha(1,in))[source(self)].
tablero(celda(1,5,0),ficha(4,in))[source(self)].
tablero(celda(8,5,0),ficha(3,in))[source(self)].
tablero(celda(3,4,0),ficha(1,in))[source(self)].
tablero(celda(5,2,0),ficha(3,in))[source(self)].
tablero(celda(7,0,0),ficha(5,in))[source(self)].
tablero(celda(4,9,0),ficha(5,in))[source(self)].
tablero(celda(0,1,0),ficha(1,in))[source(self)].
tablero(celda(7,1,0),ficha(0,in))[source(self)].
tablero(celda(5,0,0),ficha(1,in))[source(self)].
tablero(celda(9,8,0),ficha(5,in))[source(self)].
tablero(celda(2,9,0),ficha(1,in))[source(self)].
tablero(celda(9,9,0),ficha(0,in))[source(self)].
tablero(celda(4,7,0),ficha(3,in))[source(self)].
tablero(celda(6,5,0),ficha(5,in))[source(self)].
tablero(celda(6,6,0),ficha(0,in))[source(self)].
tablero(celda(1,4,0),ficha(3,in))[source(self)].
tablero(celda(3,2,0),ficha(5,in))[source(self)].